export interface CardOffer {
  id: string
  name: string
  bank: string
  cardType: 'Visa' | 'Mastercard' | 'AmEx'
  annualFee: number
  annualFeeWaived: boolean
  minAnnualIncome: number
  cashbackRate: number | null
  rewardsPoints: string | null
  tags: string[]
  highlights: string[]
  affiliateUrl: string
  color: string
  applyLabel: string
}

export const CARD_OFFERS: CardOffer[] = [
  {
    id: 'maybank-2-gold',
    name: 'Maybank 2 Gold & Platinum Visa',
    bank: 'Maybank',
    cardType: 'Visa',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: 0.5,
    rewardsPoints: '1x TreatsPoints on weekdays',
    tags: ['cashback', 'no-annual-fee', 'entry-level'],
    highlights: [
      'No annual fee forever',
      '5% cashback on weekends (petrol, groceries, dining)',
      'Up to 12% cashback at Maybank partner merchants',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/Maybank-2-Gold-and-Platinum-Visa-Credit-Card.html',
    color: '#FFB300',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'cimb-cash-rebate',
    name: 'CIMB Cash Rebate Platinum',
    bank: 'CIMB',
    cardType: 'Mastercard',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: 5,
    rewardsPoints: null,
    tags: ['cashback', 'no-annual-fee', 'petrol', 'grocery'],
    highlights: [
      'No annual fee forever',
      '5% cashback on petrol, grocery & pharmacy',
      '0.2% unlimited cashback on all other spend',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/CIMB-Cash-Rebate-Platinum-Mastercard.html',
    color: '#E53935',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'hong-leong-cashback',
    name: 'Hong Leong Cashback Card',
    bank: 'Hong Leong',
    cardType: 'Mastercard',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: 8,
    rewardsPoints: null,
    tags: ['cashback', 'no-annual-fee', 'contactless'],
    highlights: [
      'No annual fee forever',
      'Up to 8% cashback on selected categories',
      '0.2% base cashback on all spend',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/Hong-Leong-Cashback-Card-Mastercard.html',
    color: '#1565C0',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'public-bank-quantum',
    name: 'Public Bank Quantum Visa',
    bank: 'Public Bank',
    cardType: 'Visa',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: 5,
    rewardsPoints: null,
    tags: ['cashback', 'no-annual-fee', 'online', 'contactless'],
    highlights: [
      'No annual fee forever',
      '5% cashback on online & contactless payments',
      '0.5% cashback on all other spend',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/Public-Bank-Quantum-Visa-Credit-Card.html',
    color: '#2E7D32',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'ambank-bonuslink',
    name: 'AmBank BonusLink Visa',
    bank: 'AmBank',
    cardType: 'Visa',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: null,
    rewardsPoints: '5x BonusLink Points at Shell & Parkson',
    tags: ['rewards', 'no-annual-fee', 'petrol'],
    highlights: [
      'No annual fee forever',
      '5x BonusLink Points at Shell petrol stations',
      '2x BonusLink Points on all other spend',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/AmBank-BonusLink-Visa-Credit-Card.html',
    color: '#F4511E',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'rhb-smart',
    name: 'RHB Smart Value',
    bank: 'RHB',
    cardType: 'Mastercard',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: 2,
    rewardsPoints: null,
    tags: ['cashback', 'no-annual-fee', 'entry-level'],
    highlights: [
      'No annual fee forever',
      '2% cashback on Grab, utility & grocery',
      '0.5% cashback on all other spend',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/RHB-Smart-Value-Mastercard-Credit-Card.html',
    color: '#5E35B1',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'hsbc-amanah-advance',
    name: 'HSBC Advance Visa Platinum',
    bank: 'HSBC',
    cardType: 'Visa',
    annualFee: 180,
    annualFeeWaived: true,
    minAnnualIncome: 36000,
    cashbackRate: 8,
    rewardsPoints: null,
    tags: ['cashback', 'premium', 'travel', 'dining'],
    highlights: [
      'Annual fee waived with min RM12,000/year spend',
      'Up to 8% cashback on petrol, grocery & dining',
      'Complimentary travel insurance up to RM1M',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/HSBC-Advance-Visa-Platinum-Credit-Card.html',
    color: '#D32F2F',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'ocbc-titanium',
    name: 'OCBC Titanium Mastercard',
    bank: 'OCBC',
    cardType: 'Mastercard',
    annualFee: 200,
    annualFeeWaived: true,
    minAnnualIncome: 36000,
    cashbackRate: null,
    rewardsPoints: '10x VOYAGE Miles on shopping',
    tags: ['rewards', 'miles', 'shopping', 'premium'],
    highlights: [
      'Annual fee waived first 2 years',
      '10x VOYAGE Miles on department stores & online shopping',
      '1x VOYAGE Miles on all other spend',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/OCBC-Titanium-Mastercard-Credit-Card.html',
    color: '#00695C',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'standard-chartered-simply-cash',
    name: 'Standard Chartered Simply Cash',
    bank: 'Standard Chartered',
    cardType: 'Visa',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: 1.5,
    rewardsPoints: null,
    tags: ['cashback', 'no-annual-fee', 'flat-rate'],
    highlights: [
      'No annual fee forever',
      'Flat 1.5% cashback on ALL spend, no categories',
      'No minimum spend required',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/Standard-Chartered-Simply-Cash-Credit-Card.html',
    color: '#0277BD',
    applyLabel: 'Apply via RinggitPlus',
  },
  {
    id: 'alliance-you',
    name: 'Alliance Bank YOU Visa',
    bank: 'Alliance Bank',
    cardType: 'Visa',
    annualFee: 0,
    annualFeeWaived: false,
    minAnnualIncome: 24000,
    cashbackRate: 5,
    rewardsPoints: null,
    tags: ['cashback', 'no-annual-fee', 'dining', 'grocery'],
    highlights: [
      'No annual fee forever',
      '5% cashback on dining, grocery & online spend',
      'Auto-switch to highest cashback category monthly',
    ],
    affiliateUrl: 'https://ringgitplus.com/en/credit-card/Alliance-Bank-YOU-Visa-Credit-Card.html',
    color: '#E91E63',
    applyLabel: 'Apply via RinggitPlus',
  },
]

export const ALL_TAGS = [
  { value: 'cashback', label: 'Cashback' },
  { value: 'rewards', label: 'Rewards / Miles' },
  { value: 'no-annual-fee', label: 'No Annual Fee' },
  { value: 'petrol', label: 'Petrol' },
  { value: 'grocery', label: 'Grocery' },
  { value: 'dining', label: 'Dining' },
  { value: 'online', label: 'Online Shopping' },
  { value: 'travel', label: 'Travel' },
  { value: 'premium', label: 'Premium' },
  { value: 'entry-level', label: 'Entry Level' },
]
